version: '3'
services:
  mysql_khalil:
    image: mysql:5.7
    restart: always
    container_name: mysql_khalil
    environment:
      MYSQL_DATABASE: tpachato
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: khalil
      MYSQL_ROOT_PASSWORD: khalil

    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - 3306:3306
    expose:
      # Opens port 3306 on the container
      - 3306
      # Where our data will be persisted

  spring-back:
    image: khalilennaifer/hidev:latest
    container_name: achat
    ports:
      - 8089:8089
    depends_on:
      - mysql_khalil
    expose:
      # Opens port 3306 on the container
      - 8089
